#!/usr/bin/env python3
"""Generate a synthetic scenario corpus for exercising the rule engine.

WHAT THIS DATA IS
-----------------
Every scenario this script writes is **fabricated**. The factor levels are drawn
from a seeded pseudo-random number generator. They are not observations, not
derived from any incident record, and not derived from any site's data. No
establishment, employer, person or event is represented.

WHAT IT IS FOR
--------------
One thing only: exercising the engine. The corpus provides enough structural
variety to check that evaluation terminates, that traces stay well-formed, that
every rule in the base is reachable, and that the banding rules behave
monotonically. Those are software properties, and software properties are all a
made-up input can establish.

WHAT IT MUST NEVER BE USED FOR
------------------------------
No number computed from this corpus is an empirical finding about anything.
Band frequencies here are a property of the sampling weights below, which the
author chose. If a distribution over these scenarios appears in a paper, a
README or a slide as though it described real work, that is a fabrication.
The generator writes a ``synthetic: true`` flag and a provenance string into
every file, the loader carries both through, and the assessment report prints a
banner. ``tests/test_synthetic.py`` fails if any of that is missing.

DETERMINISM
-----------
Output is a pure function of ``--seed`` and ``--count``. Regenerating with the
same arguments reproduces the corpus byte for byte, so the committed files can
be checked rather than trusted.

Usage::

    python3 synthetic/generate_scenarios.py                 # default corpus
    python3 synthetic/generate_scenarios.py --check         # verify on disk
    python3 synthetic/generate_scenarios.py --count 60 --seed 7
"""

from __future__ import annotations

import argparse
import json
import os
import random
import shutil
import sys
from typing import Dict, List, Mapping, Optional, Sequence, Tuple

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_REPO_ROOT, "src"))

from ehs_hfo.ontology import Ontology  # noqa: E402

__all__ = [
    "SYNTHETIC_HEADER",
    "SCENARIO_DIR",
    "DEFAULT_SEED",
    "DEFAULT_COUNT",
    "generate_corpus",
    "write_corpus",
]

SCENARIO_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "scenarios")
DEFAULT_SEED = 20260904
DEFAULT_COUNT = 48

#: Stamped into every generated file. ``tests/test_synthetic.py`` asserts that
#: every file on disk carries it verbatim.
SYNTHETIC_HEADER = (
    "SYNTHETIC DATA. Generated by synthetic/generate_scenarios.py from a seeded "
    "pseudo-random number generator. Not an observation, not derived from any "
    "incident record, and not derived from any site's data. No establishment, "
    "employer, person or event is represented. It exists only to exercise the "
    "rule engine. No number computed from this corpus is an empirical finding."
)

#: Sampling weights over factor levels, by scenario archetype.
#:
#: Weights are keyed by the level's ``ehs:ordinalRank`` rather than by its CURIE,
#: and the ranks are resolved against the ontology at generation time. That is
#: deliberate: naming levels here would let this file drift out of step with the
#: Turtle, and an invented level name would only surface as a runtime error.
#: Ranks are 2 enhanced, 1 nominal, 0 degraded, -1 severely degraded. Rank -99
#: (unknown) is never sampled — omission is handled separately by
#: ``_OMISSION_RATE``, because "not assessed" is an absence, not a level choice.
#:
#: These are the author's choices. They encode no claim about how often real work
#: looks like this, and a frequency computed over the corpus measures only this
#: table.
_ARCHETYPES: Tuple[Tuple[str, str, Mapping[int, float]], ...] = (
    (
        "routine",
        "Routine work under settled conditions.",
        {2: 0.20, 1: 0.68, 0: 0.10, -1: 0.02},
    ),
    (
        "mixed",
        "Ordinary work with some conditions off nominal.",
        {2: 0.10, 1: 0.55, 0: 0.27, -1: 0.08},
    ),
    (
        "strained",
        "Several conditions degraded at once.",
        {2: 0.04, 1: 0.36, 0: 0.42, -1: 0.18},
    ),
    (
        "nonroutine",
        "Non-routine intervention with weak procedural cover.",
        {2: 0.02, 1: 0.28, 0: 0.42, -1: 0.28},
    ),
)

#: Probability that a given factor is left unassessed, by archetype. Present so
#: the corpus exercises the unknown-level path, which is the one a screening
#: tool most often gets wrong in practice.
_OMISSION_RATE: Mapping[str, float] = {
    "routine": 0.02,
    "mixed": 0.06,
    "strained": 0.10,
    "nonroutine": 0.16,
}

#: Probability a degraded factor carries a claimed control.
_MITIGATION_RATE: Mapping[str, float] = {
    "routine": 0.55,
    "mixed": 0.40,
    "strained": 0.28,
    "nonroutine": 0.20,
}


def _weighted_choice(rng: random.Random, weights: Mapping[str, float]) -> str:
    """Pick a key from ``weights`` in proportion to its value.

    Keys are iterated in sorted order so the draw is reproducible across runs
    and Python versions, independent of dict insertion order.
    """
    total = sum(weights.values())
    threshold = rng.random() * total
    cumulative = 0.0
    for key, weight in sorted(weights.items()):
        cumulative += weight
        if threshold <= cumulative:
            return key
    return sorted(weights)[-1]  # pragma: no cover - float edge case


def _resolve_rank_weights(
    weights: Mapping[int, float], ontology: Ontology
) -> Dict[str, float]:
    """Turn rank-keyed weights into CURIE-keyed weights using the ontology.

    Raises if a rank names no level, or names more than one. Both would mean the
    ontology's level scheme changed under this generator, and guessing would put
    fabricated levels into the corpus.
    """
    by_rank: Dict[int, List[str]] = {}
    for curie, level in ontology.levels.items():
        by_rank.setdefault(level.rank, []).append(curie)

    resolved: Dict[str, float] = {}
    for rank, weight in weights.items():
        matches = sorted(by_rank.get(rank, []))
        if len(matches) != 1:
            raise RuntimeError(
                f"ordinal rank {rank} resolves to {len(matches)} levels "
                f"({', '.join(matches) or 'none'}); the generator's weight table "
                f"is out of step with ontology/ehs-hfo.ttl"
            )
        resolved[matches[0]] = weight
    return resolved


def _make_scenario(
    rng: random.Random,
    index: int,
    archetype: str,
    archetype_note: str,
    weights: Mapping[str, float],
    factor_curies: Sequence[str],
    degraded_levels: Sequence[str],
) -> Dict[str, object]:
    """Build one synthetic scenario payload."""
    levels: Dict[str, str] = {}
    omission = _OMISSION_RATE[archetype]
    for curie in factor_curies:
        if rng.random() < omission:
            continue
        levels[curie] = _weighted_choice(rng, weights)

    mitigations: Dict[str, List[str]] = {}
    mitigation_rate = _MITIGATION_RATE[archetype]
    for curie, level in sorted(levels.items()):
        if level in degraded_levels and rng.random() < mitigation_rate:
            local = curie.split(":", 1)[1]
            mitigations[curie] = [f"SYN-CTRL-{local}-{index:03d}"]

    return {
        "scenario_id": f"syn-{archetype}-{index:03d}",
        "description": (
            f"Synthetic scenario {index:03d} ({archetype}). {archetype_note} "
            "Fabricated by a seeded generator; describes no real work."
        ),
        "synthetic": True,
        "provenance": SYNTHETIC_HEADER,
        "generator": {
            "script": "synthetic/generate_scenarios.py",
            "archetype": archetype,
            "note": (
                "Levels sampled from author-chosen weights. Any frequency "
                "computed over this corpus measures those weights, nothing else."
            ),
        },
        "factor_levels": dict(sorted(levels.items())),
        "mitigations": dict(sorted(mitigations.items())),
    }


def generate_corpus(
    count: int = DEFAULT_COUNT,
    seed: int = DEFAULT_SEED,
    ontology: Optional[Ontology] = None,
) -> List[Dict[str, object]]:
    """Generate ``count`` synthetic scenarios deterministically from ``seed``."""
    ontology = ontology or Ontology.load()
    factor_curies = sorted(ontology.factors)
    degraded_levels = sorted(
        curie for curie, level in ontology.levels.items() if level.is_degraded
    )
    if not degraded_levels:  # pragma: no cover - guards an ontology edit
        raise RuntimeError("ontology declares no degraded levels")

    resolved = {
        name: _resolve_rank_weights(weights, ontology)
        for name, _, weights in _ARCHETYPES
    }

    rng = random.Random(seed)
    scenarios: List[Dict[str, object]] = []
    for index in range(count):
        archetype, note, _ = _ARCHETYPES[index % len(_ARCHETYPES)]
        scenarios.append(
            _make_scenario(
                rng,
                index,
                archetype,
                note,
                resolved[archetype],
                factor_curies,
                degraded_levels,
            )
        )
    return scenarios


def _render(scenario: Mapping[str, object]) -> str:
    """Serialise one scenario to the exact text written to disk."""
    return json.dumps(scenario, indent=2, sort_keys=False) + "\n"


def write_corpus(
    scenarios: Sequence[Mapping[str, object]], out_dir: str = SCENARIO_DIR
) -> List[str]:
    """Write the corpus, replacing any previous contents of ``out_dir``."""
    if os.path.isdir(out_dir):
        shutil.rmtree(out_dir)
    os.makedirs(out_dir, exist_ok=True)
    paths: List[str] = []
    for scenario in scenarios:
        path = os.path.join(out_dir, f"{scenario['scenario_id']}.json")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(_render(scenario))
        paths.append(path)
    return paths


def _check(scenarios: Sequence[Mapping[str, object]], out_dir: str) -> List[str]:
    """Return a list of problems; empty means the corpus on disk is current."""
    problems: List[str] = []
    expected = {f"{s['scenario_id']}.json": _render(s) for s in scenarios}
    actual = (
        set(os.listdir(out_dir)) if os.path.isdir(out_dir) else set()
    )
    actual = {name for name in actual if name.endswith(".json")}

    for name in sorted(set(expected) - actual):
        problems.append(f"{name}: missing")
    for name in sorted(actual - set(expected)):
        problems.append(f"{name}: unexpected file on disk")
    for name in sorted(set(expected) & actual):
        with open(os.path.join(out_dir, name), encoding="utf-8") as handle:
            if handle.read() != expected[name]:
                problems.append(f"{name}: content differs from generator output")
    return problems


def main(argv: Optional[Sequence[str]] = None) -> int:
    """Command line entry point."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--count", type=int, default=DEFAULT_COUNT)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--out-dir", default=SCENARIO_DIR)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the corpus on disk is not reproducible",
    )
    args = parser.parse_args(argv)

    scenarios = generate_corpus(count=args.count, seed=args.seed)

    if args.check:
        problems = _check(scenarios, args.out_dir)
        if problems:
            for line in problems:
                print(line, file=sys.stderr)
            print(
                "run: python3 synthetic/generate_scenarios.py", file=sys.stderr
            )
            return 1
        print(f"synthetic corpus is reproducible ({len(scenarios)} scenarios)")
        return 0

    paths = write_corpus(scenarios, args.out_dir)
    print(
        f"wrote {len(paths)} synthetic scenarios to "
        f"{os.path.relpath(args.out_dir, _REPO_ROOT)} "
        f"(seed={args.seed})"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
